### ISSUE TITLE
title slips low - archive sheet - desktop safari

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#45] opened 2017-04-22 18:09 UTC
some titles slip low over the divider line, icon, and image
(this is an issue for an older version of safari - 9.1.3 - so if this is tricky we can figure out if we want to correct for this browser version)

<img width="1009" alt="screen shot 2017-04-22 at 2 15 20 pm" src="https://cloud.githubusercontent.com/assets/20864185/25306895/3e918a9e-2765-11e7-9205-9ec59095e92d.png">

**Comment by ebrelsford** [comment] 2017-04-27 14:21
Duplicate of #32

**Closed as completed by ebrelsford** 2017-04-27 14:21 UTC
