### ISSUE TITLE
title/parchment page - artifact sheet - desktop safari

### ISSUE THREAD

**Issue by a-murry** [uofo/reverse-archaeology#46] opened 2017-04-22 18:13 UTC
Some icons run off top of page

<img width="1007" alt="screen shot 2017-04-22 at 2 18 41 pm" src="https://cloud.githubusercontent.com/assets/20864185/25306922/bbf290aa-2765-11e7-8061-6d4f702929d0.png">

**Comment by ebrelsford** [comment] 2017-04-24 20:08
Duplicate of #45

**Closed as completed by ebrelsford** 2017-04-24 20:08 UTC
